### PR TITLE
Improved the handling of the dat file loading

### PR DESCRIPTION
**Pull request by burzum**

### CODE REVIEW

**Comment by sime** [comment]
My 2c, this project uses PEAR coding standards.

**Comment by burzum** [comment]
Well, it is a CakePHP plugin, so why does it use PEAR standards and not Cakes?

**Comment by sime** [comment]
Author's preference.

On Fri, Nov 8, 2013 at 6:27 PM, Florian Krämer notifications@github.comwrote:

> Well, it is a CakePHP plugin, so why does it use PEAR standards and not
> Cakes?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Pollenizer/CakePHP-GeoIP-Plugin/pull/3#issuecomment-28053502
> .

## 

Simon Males

**Comment by burzum** [comment]
Feel free to change the coding standard then, from my side the job is done.

**Pull request closed without merging**
